# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-14 23:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments_records_id', models.IntegerField()),
                ('comments_users_id', models.IntegerField()),
                ('comments_users_first', models.TextField()),
                ('comments_users_last', models.TextField()),
                ('comments_users_date', models.DateTimeField()),
                ('comments_users_text', models.TextField(verbose_name='Комментарий')),
                ('comments_users_like_id', models.TextField(default='')),
                ('comments_users_like', models.IntegerField(default=0)),
                ('answer_users_id', models.IntegerField(null=True)),
                ('answer_users_first', models.TextField(default='')),
                ('answer_users_last', models.TextField(default='')),
                ('answer_users_date', models.DateTimeField(null=True)),
                ('answer_users_text', models.TextField(default='')),
                ('answer_users_like_id', models.TextField(default='')),
                ('answer_users_like', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'comments',
            },
        ),
        migrations.CreateModel(
            name='PhotoAlbom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abpho_user_id', models.IntegerField(default=0)),
                ('abpho_user_albom_id', models.IntegerField(default=0)),
                ('abpho_user_photo', models.ImageField(upload_to='static/photo')),
                ('abpho_user_photo_date', models.DateTimeField(null=True)),
                ('abpho_user_photo_like_id', models.TextField(default='')),
                ('abpho_user_photo_like', models.IntegerField(default=0)),
                ('abpho_user_photo_ava', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'albomphoto',
            },
        ),
        migrations.CreateModel(
            name='Records',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('records_inuser_id', models.IntegerField()),
                ('records_user_id', models.IntegerField(default=0)),
                ('records_user_first', models.TextField()),
                ('records_user_last', models.TextField()),
                ('records_text', models.TextField(verbose_name='Запись')),
                ('records_date', models.DateTimeField()),
                ('records_likes_id', models.TextField()),
                ('records_likes', models.IntegerField(default=0)),
                ('records_repost', models.IntegerField(default=0)),
                ('records_repost_id', models.TextField()),
                ('repost_repost_user_id', models.IntegerField(null=True)),
                ('repost_repost_first', models.TextField(default='')),
                ('repost_repost_last', models.TextField(default='')),
                ('repost_repost_date', models.DateTimeField(null=True)),
                ('repost_repost_likes_id', models.TextField(default='')),
                ('repost_repost_likes', models.IntegerField(default=0)),
                ('repost_repost', models.IntegerField(default=0)),
                ('repost_repost_id', models.TextField(default='')),
            ],
            options={
                'db_table': 'records',
            },
        ),
    ]
