# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-14 23:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsMessages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_user_id', models.IntegerField(default=0)),
                ('message_user_name', models.TextField(default='')),
                ('message_outuser_id', models.IntegerField(default=0)),
                ('message_outuser_name', models.TextField(default='')),
                ('message_text', models.TextField(default='')),
                ('message_date', models.DateTimeField(default=0)),
                ('message_name', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'usmessages',
            },
        ),
    ]
