# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-15 04:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usmessages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usmessages',
            name='message_see',
            field=models.IntegerField(default=0),
        ),
    ]
